name: fixit
description: A crowdsourced infrastructure reporting mobile application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.1
  
  # Icons & UI
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
